name: kerjoy
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0 <3.0.0"
  
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_staggered_grid_view: ^0.2.7
  flutter_calendar_carousel: ^1.3.11
  pinput: ^0.1.6
  flutter_fluid_slider: ^0.0.1
  pit_components: ^0.0.19
  cloud_firestore: ^0.9.0
  firebase_auth: ^0.8.0+1
  firebase_database: ^2.0.0
  firebase_storage: ^2.0.0
  image_picker: ^0.5.0+1 
  shared_preferences: ^0.5.0
  google_sign_in: ^4.0.0
  flutter_facebook_login: ^1.2.0
  multi_image_picker: ^3.0.11
  material_design_icons_flutter: ^3.0.3392
  path_provider: ^0.5.0
  image: ^2.0.6
  intl: ^0.15.7
  fluttertoast: ^2.2.11



dev_dependencies:
  intl_translation: ^0.17.2

  flutter_test:
    sdk: flutter



# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: mermaid
      fonts:
        - asset: assets/fonts/Mermaid1001.ttf
    - family: bebas-neue
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf
    - family: roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
  assets:
    - assets/images/add_new.png
    - assets/images/add_photo.png
    - assets/images/arrive.png
    - assets/images/arrow_grey_left.png
    - assets/images/arrow_grey_right.png
    - assets/images/back.png
    - assets/images/back.jpg
    - assets/images/boxer.png
    - assets/images/calendar.png
    - assets/images/camera.png
    - assets/images/cancel_round.png
    - assets/images/cancel.png
    - assets/images/care_provided_color.png
    - assets/images/care_provided_grey.png
    - assets/images/care.png
    - assets/images/cheese.png
    - assets/images/childback.jpg
    - assets/images/cookie.png
    - assets/images/crying.png
    - assets/images/default_profile.png
    - assets/images/diagnosis_color.png
    - assets/images/diagnosis_grey.png
    - assets/images/diaper_icon_three.png
    - assets/images/diaper_icon_two.png
    - assets/images/diaper_rating.png
    - assets/images/diaper.png
    - assets/images/ear_drop.png
    - assets/images/ear_pain.png
    - assets/images/email.png
    - assets/images/emoji_four.png
    - assets/images/emoji_one.png
    - assets/images/emoji_two.png
    - assets/images/emoji_three.png
    - assets/images/eye_cleaning.png
    - assets/images/eye_drop.png
    - assets/images/fever.png
    - assets/images/food.png
    - assets/images/free.png
    - assets/images/fruit.png
    - assets/images/green_tick.png
    - assets/images/jumping.png
    - assets/images/leave.png
    - assets/images/leave_blue.png
    - assets/images/medication_color.png
    - assets/images/medication_grey.png
    - assets/images/menu.png
    - assets/images/moisturizer.png
    - assets/images/next_round.png
    - assets/images/nose_cleaning.png
    - assets/images/other.png
    - assets/images/painting.png
    - assets/images/paracetamol.png
    - assets/images/password.png
    - assets/images/play.png
    - assets/images/reading.png
    - assets/images/right_arrow_white.png
    - assets/images/runny_nose.png
    - assets/images/singing.png
    - assets/images/sleep.png
    - assets/images/sleeping.png
    - assets/images/three_dot.png
    - assets/images/toothache.png
    - assets/images/tshirt_round.png
    - assets/images/vitamin.png
    - assets/images/vomiting.png
    - assets/images/wake_up.png
    - assets/images/child.jpg
    - assets/images/childrentime.jpg
    - assets/svgs/diaper_icon_three.svg


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
